
 export const voices = [
    { id: "af-ZA-AdriNeural", locale: "af-ZA", gender: "Female", name: "Adri" },
    { id: "af-ZA-WillemNeural", locale: "af-ZA", gender: "Male", name: "Willem" },
    { id: "sq-AL-AnilaNeural", locale: "sq-AL", gender: "Female", name: "Anila" },
    { id: "sq-AL-IlirNeural", locale: "sq-AL", gender: "Male", name: "Ilir" },
    { id: "am-ET-AmehaNeural", locale: "am-ET", gender: "Male", name: "Ameha" },
    {
      id: "am-ET-MekdesNeural",
      locale: "am-ET",
      gender: "Female",
      name: "Mekdes",
    },
    { id: "ar-DZ-AminaNeural", locale: "ar-DZ", gender: "Female", name: "Amina" },
    { id: "ar-DZ-IsmaelNeural", locale: "ar-DZ", gender: "Male", name: "Ismael" },
    { id: "ar-BH-AliNeural", locale: "ar-BH", gender: "Male", name: "Ali" },
    { id: "ar-BH-LailaNeural", locale: "ar-BH", gender: "Female", name: "Laila" },
    { id: "ar-EG-SalmaNeural", locale: "ar-EG", gender: "Female", name: "Salma" },
    { id: "ar-EG-ShakirNeural", locale: "ar-EG", gender: "Male", name: "Shakir" },
    { id: "ar-IQ-BasselNeural", locale: "ar-IQ", gender: "Male", name: "Bassel" },
    { id: "ar-IQ-RanaNeural", locale: "ar-IQ", gender: "Female", name: "Rana" },
    { id: "ar-JO-SanaNeural", locale: "ar-JO", gender: "Female", name: "Sana" },
    { id: "ar-JO-TaimNeural", locale: "ar-JO", gender: "Male", name: "Taim" },
    { id: "ar-KW-FahedNeural", locale: "ar-KW", gender: "Male", name: "Fahed" },
    { id: "ar-KW-NouraNeural", locale: "ar-KW", gender: "Female", name: "Noura" },
    { id: "ar-LB-LaylaNeural", locale: "ar-LB", gender: "Female", name: "Layla" },
    { id: "ar-LB-RamiNeural", locale: "ar-LB", gender: "Male", name: "Rami" },
    { id: "ar-LY-ImanNeural", locale: "ar-LY", gender: "Female", name: "Iman" },
    { id: "ar-LY-OmarNeural", locale: "ar-LY", gender: "Male", name: "Omar" },
    { id: "ar-MA-JamalNeural", locale: "ar-MA", gender: "Male", name: "Jamal" },
    { id: "ar-MA-MounaNeural", locale: "ar-MA", gender: "Female", name: "Mouna" },
    {
      id: "ar-OM-AbdullahNeural",
      locale: "ar-OM",
      gender: "Male",
      name: "Abdullah",
    },
    { id: "ar-OM-AyshaNeural", locale: "ar-OM", gender: "Female", name: "Aysha" },
    { id: "ar-QA-AmalNeural", locale: "ar-QA", gender: "Female", name: "Amal" },
    { id: "ar-QA-MoazNeural", locale: "ar-QA", gender: "Male", name: "Moaz" },
    { id: "ar-SA-HamedNeural", locale: "ar-SA", gender: "Male", name: "Hamed" },
    {
      id: "ar-SA-ZariyahNeural",
      locale: "ar-SA",
      gender: "Female",
      name: "Zariyah",
    },
    { id: "ar-SY-AmanyNeural", locale: "ar-SY", gender: "Female", name: "Amany" },
    { id: "ar-SY-LaithNeural", locale: "ar-SY", gender: "Male", name: "Laith" },
    { id: "ar-TN-HediNeural", locale: "ar-TN", gender: "Male", name: "Hedi" },
    { id: "ar-TN-ReemNeural", locale: "ar-TN", gender: "Female", name: "Reem" },
    {
      id: "ar-AE-FatimaNeural",
      locale: "ar-AE",
      gender: "Female",
      name: "Fatima",
    },
    { id: "ar-AE-HamdanNeural", locale: "ar-AE", gender: "Male", name: "Hamdan" },
    {
      id: "ar-YE-MaryamNeural",
      locale: "ar-YE",
      gender: "Female",
      name: "Maryam",
    },
    { id: "ar-YE-SalehNeural", locale: "ar-YE", gender: "Male", name: "Saleh" },
    { id: "az-AZ-BabekNeural", locale: "az-AZ", gender: "Male", name: "Babek" },
    { id: "az-AZ-BanuNeural", locale: "az-AZ", gender: "Female", name: "Banu" },
    {id: "ga-IE-ColmNeural", locale: "ga-IE", gender: "Male", name: "Colm"},
  {id: "ga-IE-OrlaNeural", locale: "ga-IE", gender: "Female", name: "Orla"},
  {id: "it-IT-GiuseppeMultilingualNeural", locale: "it-IT", gender: "Male", name: "GiuseppeMultilingual"},
  {id: "it-IT-DiegoNeural", locale: "it-IT", gender: "Male", name: "Diego"},
  {id: "it-IT-ElsaNeural", locale: "it-IT", gender: "Female", name: "Elsa"},
  {id: "it-IT-IsabellaNeural", locale: "it-IT", gender: "Female", name: "Isabella"},
  {id: "ja-JP-KeitaNeural", locale: "ja-JP", gender: "Male", name: "Keita"},
  {id: "ja-JP-NanamiNeural", locale: "ja-JP", gender: "Female", name: "Nanami"},
  {id: "jv-ID-DimasNeural", locale: "jv-ID", gender: "Male", name: "Dimas"},
  {id: "jv-ID-SitiNeural", locale: "jv-ID", gender: "Female", name: "Siti"},
  {id: "kn-IN-GaganNeural", locale: "kn-IN", gender: "Male", name: "Gagan"},
  {id: "kn-IN-SapnaNeural", locale: "kn-IN", gender: "Female", name: "Sapna"},
  {id: "kk-KZ-AigulNeural", locale: "kk-KZ", gender: "Female", name: "Aigul"},
  {id: "kk-KZ-DauletNeural", locale: "kk-KZ", gender: "Male", name: "Daulet"},
  {id: "km-KH-PisethNeural", locale: "km-KH", gender: "Male", name: "Piseth"},
  {id: "km-KH-SreymomNeural", locale: "km-KH", gender: "Female", name: "Sreymom"},
  {id: "ko-KR-HyunsuMultilingualNeural", locale: "ko-KR", gender: "Male", name: "HyunsuMultilingual"},
  {id: "ko-KR-InJoonNeural", locale: "ko-KR", gender: "Male", name: "InJoon"},
  {id: "ko-KR-SunHiNeural", locale: "ko-KR", gender: "Female", name: "SunHi"},
  {id: "lo-LA-ChanthavongNeural", locale: "lo-LA", gender: "Male", name: "Chanthavong"},
  {id: "lo-LA-KeomanyNeural", locale: "lo-LA", gender: "Female", name: "Keomany"},
  {id: "lv-LV-EveritaNeural", locale: "lv-LV", gender: "Female", name: "Everita"},
  {id: "lv-LV-NilsNeural", locale: "lv-LV", gender: "Male", name: "Nils"},
  {id: "lt-LT-LeonasNeural", locale: "lt-LT", gender: "Male", name: "Leonas"},
  {id: "lt-LT-OnaNeural", locale: "lt-LT", gender: "Female", name: "Ona"},
  {id: "mk-MK-AleksandarNeural", locale: "mk-MK", gender: "Male", name: "Aleksandar"},
  {id: "mk-MK-MarijaNeural", locale: "mk-MK", gender: "Female", name: "Marija"},
  {id: "ms-MY-OsmanNeural", locale: "ms-MY", gender: "Male", name: "Osman"},
  {id: "ms-MY-YasminNeural", locale: "ms-MY", gender: "Female", name: "Yasmin"},
  {id: "ml-IN-MidhunNeural", locale: "ml-IN", gender: "Male", name: "Midhun"},
  {id: "ml-IN-SobhanaNeural", locale: "ml-IN", gender: "Female", name: "Sobhana"},
  {id: "mt-MT-GraceNeural", locale: "mt-MT", gender: "Female", name: "Grace"},
  {id: "mt-MT-JosephNeural", locale: "mt-MT", gender: "Male", name: "Joseph"},
  {id: "mr-IN-AarohiNeural", locale: "mr-IN", gender: "Female", name: "Aarohi"},
  {id: "mr-IN-ManoharNeural", locale: "mr-IN", gender: "Male", name: "Manohar"},
  {id: "mn-MN-BataaNeural", locale: "mn-MN", gender: "Male", name: "Bataa"},
  {id: "mn-MN-YesuiNeural", locale: "mn-MN", gender: "Female", name: "Yesui"},
  {id: "ne-NP-HemkalaNeural", locale: "ne-NP", gender: "Female", name: "Hemkala"},
  {id: "ne-NP-SagarNeural", locale: "ne-NP", gender: "Male", name: "Sagar"},
  {id: "nb-NO-FinnNeural", locale: "nb-NO", gender: "Male", name: "Finn"},
  {id: "nb-NO-PernilleNeural", locale: "nb-NO", gender: "Female", name: "Pernille"},
  {id: "ps-AF-GulNawazNeural", locale: "ps-AF", gender: "Male", name: "GulNawaz"},
  {id: "ps-AF-LatifaNeural", locale: "ps-AF", gender: "Female", name: "Latifa"},
  {id: "fa-IR-DilaraNeural", locale: "fa-IR", gender: "Female", name: "Dilara"},
  {id: "fa-IR-FaridNeural", locale: "fa-IR", gender: "Male", name: "Farid"},
  {id: "pl-PL-MarekNeural", locale: "pl-PL", gender: "Male", name: "Marek"},
  {id: "pl-PL-ZofiaNeural", locale: "pl-PL", gender: "Female", name: "Zofia"},
  {id: "pt-BR-ThalitaMultilingualNeural", locale: "pt-BR", gender: "Female", name: "ThalitaMultilingual"},
  {id: "pt-BR-AntonioNeural", locale: "pt-BR", gender: "Male", name: "Antonio"},
  {id: "pt-BR-FranciscaNeural", locale: "pt-BR", gender: "Female", name: "Francisca"},
  {id: "pt-PT-DuarteNeural", locale: "pt-PT", gender: "Male", name: "Duarte"},
  {id: "pt-PT-RaquelNeural", locale: "pt-PT", gender: "Female", name: "Raquel"},
  {id: "ro-RO-AlinaNeural", locale: "ro-RO", gender: "Female", name: "Alina"},
  {id: "ro-RO-EmilNeural", locale: "ro-RO", gender: "Male", name: "Emil"},
  {id: "ru-RU-DmitryNeural", locale: "ru-RU", gender: "Male", name: "Dmitry"},
  {id: "ru-RU-SvetlanaNeural", locale: "ru-RU", gender: "Female", name: "Svetlana"},
  {id: "sr-RS-NicholasNeural", locale: "sr-RS", gender: "Male", name: "Nicholas"},
  {id: "sr-RS-SophieNeural", locale: "sr-RS", gender: "Female", name: "Sophie"},
  {id: "si-LK-SameeraNeural", locale: "si-LK", gender: "Male", name: "Sameera"},
  {id: "si-LK-ThiliniNeural", locale: "si-LK", gender: "Female", name: "Thilini"},
  {id: "sk-SK-LukasNeural", locale: "sk-SK", gender: "Male", name: "Lukas"},
  {id: "sk-SK-ViktoriaNeural", locale: "sk-SK", gender: "Female", name: "Viktoria"},
  {id: "sl-SI-PetraNeural", locale: "sl-SI", gender: "Female", name: "Petra"},
  {id: "sl-SI-RokNeural", locale: "sl-SI", gender: "Male", name: "Rok"},
  {id: "so-SO-MuuseNeural", locale: "so-SO", gender: "Male", name: "Muuse"},
  {id: "so-SO-UbaxNeural", locale: "so-SO", gender: "Female", name: "Ubax"},
  {id: "es-AR-ElenaNeural", locale: "es-AR", gender: "Female", name: "Elena"},
  {id: "es-AR-TomasNeural", locale: "es-AR", gender: "Male", name: "Tomas"},
  {id: "es-BO-MarceloNeural", locale: "es-BO", gender: "Male", name: "Marcelo"},
  {id: "es-BO-SofiaNeural", locale: "es-BO", gender: "Female", name: "Sofia"},
  {id: "es-CL-CatalinaNeural", locale: "es-CL", gender: "Female", name: "Catalina"},
  {id: "es-CL-LorenzoNeural", locale: "es-CL", gender: "Male", name: "Lorenzo"},
  {id: "es-CO-GonzaloNeural", locale: "es-CO", gender: "Male", name: "Gonzalo"},
  {id: "es-CO-SalomeNeural", locale: "es-CO", gender: "Female", name: "Salome"},
  {id: "es-ES-XimenaNeural", locale: "es-ES", gender: "Female", name: "Ximena"},
  {id: "es-CR-JuanNeural", locale: "es-CR", gender: "Male", name: "Juan"},
  {id: "es-CR-MariaNeural", locale: "es-CR", gender: "Female", name: "Maria"},
  {id: "es-CU-BelkysNeural", locale: "es-CU", gender: "Female", name: "Belkys"},
  {id: "es-CU-ManuelNeural", locale: "es-CU", gender: "Male", name: "Manuel"},
  {id: "es-DO-EmilioNeural", locale: "es-DO", gender: "Male", name: "Emilio"},
  {id: "es-DO-RamonaNeural", locale: "es-DO", gender: "Female", name: "Ramona"},
  {id: "es-EC-AndreaNeural", locale: "es-EC", gender: "Female", name: "Andrea"},
  {id: "es-EC-LuisNeural", locale: "es-EC", gender: "Male", name: "Luis"},
  {id: "es-SV-LorenaNeural", locale: "es-SV", gender: "Female", name: "Lorena"},
  {id: "es-SV-RodrigoNeural", locale: "es-SV", gender: "Male", name: "Rodrigo"},
  {id: "es-GQ-JavierNeural", locale: "es-GQ", gender: "Male", name: "Javier"},
  {id: "es-GQ-TeresaNeural", locale: "es-GQ", gender: "Female", name: "Teresa"},
  {id: "es-GT-AndresNeural", locale: "es-GT", gender: "Male", name: "Andres"},
  {id: "es-GT-MartaNeural", locale: "es-GT", gender: "Female", name: "Marta"},
  {id: "es-HN-CarlosNeural", locale: "es-HN", gender: "Male", name: "Carlos"},
  {id: "es-HN-KarlaNeural", locale: "es-HN", gender: "Female", name: "Karla"},
  {id: "es-MX-DaliaNeural", locale: "es-MX", gender: "Female", name: "Dalia"},
  {id: "es-MX-JorgeNeural", locale: "es-MX", gender: "Male", name: "Jorge"},
  {id: "es-NI-FedericoNeural", locale: "es-NI", gender: "Male", name: "Federico"},
  {id: "es-NI-YolandaNeural", locale: "es-NI", gender: "Female", name: "Yolanda"},
  {id: "es-PA-MargaritaNeural", locale: "es-PA", gender: "Female", name: "Margarita"},
  {id: "es-PA-RobertoNeural", locale: "es-PA", gender: "Male", name: "Roberto"},
  {id: "es-PY-MarioNeural", locale: "es-PY", gender: "Male", name: "Mario"},
  {id: "es-PY-TaniaNeural", locale: "es-PY", gender: "Female", name: "Tania"},
  {id: "es-PE-AlexNeural", locale: "es-PE", gender: "Male", name: "Alex"},
  {id: "es-PE-CamilaNeural", locale: "es-PE", gender: "Female", name: "Camila"},
  {id: "es-PR-KarinaNeural", locale: "es-PR", gender: "Female", name: "Karina"},
  {id: "es-PR-VictorNeural", locale: "es-PR", gender: "Male", name: "Victor"},
  {id: "es-ES-AlvaroNeural", locale: "es-ES", gender: "Male", name: "Alvaro"},
  {id: "es-ES-ElviraNeural", locale: "es-ES", gender: "Female", name: "Elvira"},
  {id: "es-US-AlonsoNeural", locale: "es-US", gender: "Male", name: "Alonso"},
  {id: "es-US-PalomaNeural", locale: "es-US", gender: "Female", name: "Paloma"},
  {id: "es-UY-MateoNeural", locale: "es-UY", gender: "Male", name: "Mateo"},
  {id: "es-UY-ValentinaNeural", locale: "es-UY", gender: "Female", name: "Valentina"},
  {id: "es-VE-PaolaNeural", locale: "es-VE", gender: "Female", name: "Paola"},
  {id: "es-VE-SebastianNeural", locale: "es-VE", gender: "Male", name: "Sebastian"},
  {id: "su-ID-JajangNeural", locale: "su-ID", gender: "Male", name: "Jajang"},
  {id: "su-ID-TutiNeural", locale: "su-ID", gender: "Female", name: "Tuti"},
  {id: "sw-KE-RafikiNeural", locale: "sw-KE", gender: "Male", name: "Rafiki"},
  {id: "sw-KE-ZuriNeural", locale: "sw-KE", gender: "Female", name: "Zuri"},
  {id: "sw-TZ-DaudiNeural", locale: "sw-TZ", gender: "Male", name: "Daudi"},
  {id: "sw-TZ-RehemaNeural", locale: "sw-TZ", gender: "Female", name: "Rehema"},
  {id: "sv-SE-MattiasNeural", locale: "sv-SE", gender: "Male", name: "Mattias"},
  {id: "sv-SE-SofieNeural", locale: "sv-SE", gender: "Female", name: "Sofie"},
  {id: "ta-IN-PallaviNeural", locale: "ta-IN", gender: "Female", name: "Pallavi"},
  {id: "ta-IN-ValluvarNeural", locale: "ta-IN", gender: "Male", name: "Valluvar"},
  {id: "ta-MY-KaniNeural", locale: "ta-MY", gender: "Female", name: "Kani"},
  {id: "ta-MY-SuryaNeural", locale: "ta-MY", gender: "Male", name: "Surya"},
  {id: "ta-SG-AnbuNeural", locale: "ta-SG", gender: "Male", name: "Anbu"},
  {id: "ta-SG-VenbaNeural", locale: "ta-SG", gender: "Female", name: "Venba"},
  {id: "ta-LK-KumarNeural", locale: "ta-LK", gender: "Male", name: "Kumar"},
  {id: "ta-LK-SaranyaNeural", locale: "ta-LK", gender: "Female", name: "Saranya"},
  {id: "te-IN-MohanNeural", locale: "te-IN", gender: "Male", name: "Mohan"},
  {id: "te-IN-ShrutiNeural", locale: "te-IN", gender: "Female", name: "Shruti"},
  {id: "th-TH-NiwatNeural", locale: "th-TH", gender: "Male", name: "Niwat"},
  {id: "th-TH-PremwadeeNeural", locale: "th-TH", gender: "Female", name: "Premwadee"},
  {id: "tr-TR-AhmetNeural", locale: "tr-TR", gender: "Male", name: "Ahmet"},
  {id: "tr-TR-EmelNeural", locale: "tr-TR", gender: "Female", name: "Emel"},
  {id: "uk-UA-OstapNeural", locale: "uk-UA", gender: "Male", name: "Ostap"},
  {id: "uk-UA-PolinaNeural", locale: "uk-UA", gender: "Female", name: "Polina"},
  {id: "ur-IN-GulNeural", locale: "ur-IN", gender: "Female", name: "Gul"},
  {id: "ur-IN-SalmanNeural", locale: "ur-IN", gender: "Male", name: "Salman"},
  {id: "ur-PK-AsadNeural", locale: "ur-PK", gender: "Male", name: "Asad"},
  {id: "ur-PK-UzmaNeural", locale: "ur-PK", gender: "Female", name: "Uzma"},
  {id: "uz-UZ-MadinaNeural", locale: "uz-UZ", gender: "Female", name: "Madina"},
  {id: "uz-UZ-SardorNeural", locale: "uz-UZ", gender: "Male", name: "Sardor"},
  {id: "vi-VN-HoaiMyNeural", locale: "vi-VN", gender: "Female", name: "HoaiMy"},
  {id: "vi-VN-NamMinhNeural", locale: "vi-VN", gender: "Male", name: "NamMinh"},
  {id: "cy-GB-AledNeural", locale: "cy-GB", gender: "Male", name: "Aled"},
  {id: "cy-GB-NiaNeural", locale: "cy-GB", gender: "Female", name: "Nia"},
  {id: "zu-ZA-ThandoNeural", locale: "zu-ZA", gender: "Female", name: "Thando"},
  {id: "zu-ZA-ThembaNeural", locale: "zu-ZA", gender: "Male", name: "Themba"},
  {id: "bn-BD-NabanitaNeural", locale: "bn-BD", gender: "Female", name: "Nabanita"},
  {id: "bn-BD-PradeepNeural", locale: "bn-BD", gender: "Male", name: "Pradeep"},
  {id: "bn-IN-BashkarNeural", locale: "bn-IN", gender: "Male", name: "Bashkar"},
  {id: "bn-IN-TanishaaNeural", locale: "bn-IN", gender: "Female", name: "Tanishaa"},
  {id: "bs-BA-GoranNeural", locale: "bs-BA", gender: "Male", name: "Goran"},
  {id: "bs-BA-VesnaNeural", locale: "bs-BA", gender: "Female", name: "Vesna"},
  {id: "bg-BG-BorislavNeural", locale: "bg-BG", gender: "Male", name: "Borislav"},
  {id: "bg-BG-KalinaNeural", locale: "bg-BG", gender: "Female", name: "Kalina"},
  {id: "my-MM-NilarNeural", locale: "my-MM", gender: "Female", name: "Nilar"},
  {id: "my-MM-ThihaNeural", locale: "my-MM", gender: "Male", name: "Thiha"},
  {id: "ca-ES-EnricNeural", locale: "ca-ES", gender: "Male", name: "Enric"},
  {id: "ca-ES-JoanaNeural", locale: "ca-ES", gender: "Female", name: "Joana"},
  {id: "zh-HK-HiuGaaiNeural", locale: "zh-HK", gender: "Female", name: "HiuGaai"},
  {id: "zh-HK-HiuMaanNeural", locale: "zh-HK", gender: "Female", name: "HiuMaan"},
  {id: "zh-HK-WanLungNeural", locale: "zh-HK", gender: "Male", name: "WanLung"},
  {id: "zh-CN-XiaoxiaoNeural", locale: "zh-CN", gender: "Female", name: "Xiaoxiao"},
  {id: "zh-CN-XiaoyiNeural", locale: "zh-CN", gender: "Female", name: "Xiaoyi"},
  {id: "zh-CN-YunjianNeural", locale: "zh-CN", gender: "Male", name: "Yunjian"},
  {id: "zh-CN-YunxiNeural", locale: "zh-CN", gender: "Male", name: "Yunxi"},
  {id: "zh-CN-YunxiaNeural", locale: "zh-CN", gender: "Male", name: "Yunxia"},
  {id: "zh-CN-YunyangNeural", locale: "zh-CN", gender: "Male", name: "Yunyang"}, 
  {id: "zh-TW-HsiaoChenNeural", locale: "zh-TW", gender: "Female", name: "HsiaoChen"},
  {id: "zh-TW-YunJheNeural", locale: "zh-TW", gender: "Male", name: "YunJhe"},
  {id: "zh-TW-HsiaoYuNeural", locale: "zh-TW", gender: "Female", name: "HsiaoYu"}, 
  {id: "hr-HR-GabrijelaNeural", locale: "hr-HR", gender: "Female", name: "Gabrijela"},
  {id: "hr-HR-SreckoNeural", locale: "hr-HR", gender: "Male", name: "Srecko"},
  {id: "cs-CZ-AntoninNeural", locale: "cs-CZ", gender: "Male", name: "Antonin"},
  {id: "cs-CZ-VlastaNeural", locale: "cs-CZ", gender: "Female", name: "Vlasta"},
  {id: "da-DK-ChristelNeural", locale: "da-DK", gender: "Female", name: "Christel"},
  {id: "da-DK-JeppeNeural", locale: "da-DK", gender: "Male", name: "Jeppe"},
  {id: "nl-BE-ArnaudNeural", locale: "nl-BE", gender: "Male", name: "Arnaud"},
  {id: "nl-BE-DenaNeural", locale: "nl-BE", gender: "Female", name: "Dena"},
  {id: "nl-NL-ColetteNeural", locale: "nl-NL", gender: "Female", name: "Colette"},
  {id: "nl-NL-FennaNeural", locale: "nl-NL", gender: "Female", name: "Fenna"},
  {id: "nl-NL-MaartenNeural", locale: "nl-NL", gender: "Male", name: "Maarten"},
  {id: "en-AU-NatashaNeural", locale: "en-AU", gender: "Female", name: "Natasha"},
  {id: "en-AU-WilliamNeural", locale: "en-AU", gender: "Male", name: "William"},
  {id: "en-CA-ClaraNeural", locale: "en-CA", gender: "Female", name: "Clara"},
  {id: "en-CA-LiamNeural", locale: "en-CA", gender: "Male", name: "Liam"},
  {id: "en-HK-SamNeural", locale: "en-HK", gender: "Male", name: "Sam"},
  {id: "en-HK-YanNeural", locale: "en-HK", gender: "Female", name: "Yan"},
  {id: "en-IN-NeerjaExpressiveNeural", locale: "en-IN", gender: "Female", name: "NeerjaExpressive"},
  {id: "en-IN-NeerjaNeural", locale: "en-IN", gender: "Female", name: "Neerja"},
  {id: "en-IN-PrabhatNeural", locale: "en-IN", gender: "Male", name: "Prabhat"},
  {id: "en-IE-ConnorNeural", locale: "en-IE", gender: "Male", name: "Connor"},
  {id: "en-IE-EmilyNeural", locale: "en-IE", gender: "Female", name: "Emily"},
  {id: "en-KE-AsiliaNeural", locale: "en-KE", gender: "Female", name: "Asilia"},
  {id: "en-KE-ChilembaNeural", locale: "en-KE", gender: "Male", name: "Chilemba"},
  {id: "en-NZ-MitchellNeural", locale: "en-NZ", gender: "Male", name: "Mitchell"},
  {id: "en-NZ-MollyNeural", locale: "en-NZ", gender: "Female", name: "Molly"},
  {id: "en-NG-AbeoNeural", locale: "en-NG", gender: "Male", name: "Abeo"},
  {id: "en-NG-EzinneNeural", locale: "en-NG", gender: "Female", name: "Ezinne"},
  {id: "en-PH-JamesNeural", locale: "en-PH", gender: "Male", name: "James"},
  {id: "en-PH-RosaNeural", locale: "en-PH", gender: "Female", name: "Rosa"},
  {id: "en-SG-LunaNeural", locale: "en-SG", gender: "Female", name: "Luna"},
  {id: "en-SG-WayneNeural", locale: "en-SG", gender: "Male", name: "Wayne"},
  {id: "en-US-AvaMultilingualNeural", locale: "en-US", gender: "Female", name: "AvaMultilingual"},
  {id: "en-US-AndrewMultilingualNeural", locale: "en-US", gender: "Male", name: "AndrewMultilingual"},
  {id: "en-US-EmmaMultilingualNeural", locale: "en-US", gender: "Female", name: "EmmaMultilingual"},
  {id: "en-US-BrianMultilingualNeural", locale: "en-US", gender: "Male", name: "BrianMultilingual"},
  {id: "en-US-AvaNeural", locale: "en-US", gender: "Female", name: "Ava"},
  {id: "en-US-AndrewNeural", locale: "en-US", gender: "Male", name: "Andrew"},
  {id: "en-US-EmmaNeural", locale: "en-US", gender: "Female", name: "Emma"},
  {id: "en-US-BrianNeural", locale: "en-US", gender: "Male", name: "Brian"},
  {id: "en-ZA-LeahNeural", locale: "en-ZA", gender: "Female", name: "Leah"},
  {id: "en-ZA-LukeNeural", locale: "en-ZA", gender: "Male", name: "Luke"},
  {id: "en-TZ-ElimuNeural", locale: "en-TZ", gender: "Male", name: "Elimu"},
  {id: "en-TZ-ImaniNeural", locale: "en-TZ", gender: "Female", name: "Imani"},
  {id: "en-GB-LibbyNeural", locale: "en-GB", gender: "Female", name: "Libby"},
  {id: "en-GB-MaisieNeural", locale: "en-GB", gender: "Female", name: "Maisie"},
  {id: "en-GB-RyanNeural", locale: "en-GB", gender: "Male", name: "Ryan"},
  {id: "en-GB-SoniaNeural", locale: "en-GB", gender: "Female", name: "Sonia"},
  {id: "en-GB-ThomasNeural", locale: "en-GB", gender: "Male", name: "Thomas"},
  {id: "en-US-AnaNeural", locale: "en-US", gender: "Female", name: "Ana"},
  {id: "en-US-AriaNeural", locale: "en-US", gender: "Female", name: "Aria"},
  {id: "en-US-ChristopherNeural", locale: "en-US", gender: "Male", name: "Christopher"},
  {id: "en-US-EricNeural", locale: "en-US", gender: "Male", name: "Eric"},
  {id: "en-US-GuyNeural", locale: "en-US", gender: "Male", name: "Guy"},
  {id: "en-US-JennyNeural", locale: "en-US", gender: "Female", name: "Jenny"},
  {id: "en-US-MichelleNeural", locale: "en-US", gender: "Female", name: "Michelle"},
  {id: "en-US-RogerNeural", locale: "en-US", gender: "Male", name: "Roger"},
  {id: "en-US-SteffanNeural", locale: "en-US", gender: "Male", name: "Steffan"},
  {id: "et-EE-AnuNeural", locale: "et-EE", gender: "Female", name: "Anu"},
  {id: "et-EE-KertNeural", locale: "et-EE", gender: "Male", name: "Kert"},
  {id: "fil-PH-AngeloNeural", locale: "fil-PH", gender: "Male", name: "Angelo"},
  {id: "fil-PH-BlessicaNeural", locale: "fil-PH", gender: "Female", name: "Blessica"},
  {id: "fi-FI-HarriNeural", locale: "fi-FI", gender: "Male", name: "Harri"},
  {id: "fi-FI-NooraNeural", locale: "fi-FI", gender: "Female", name: "Noora"},
  {id: "fr-BE-CharlineNeural", locale: "fr-BE", gender: "Female", name: "Charline"},
  {id: "fr-BE-GerardNeural", locale: "fr-BE", gender: "Male", name: "Gerard"},
  {id: "fr-CA-ThierryNeural", locale: "fr-CA", gender: "Male", name: "Thierry"},
  {id: "fr-CA-AntoineNeural", locale: "fr-CA", gender: "Male", name: "Antoine"},
  {id: "fr-CA-JeanNeural", locale: "fr-CA", gender: "Male", name: "Jean"},
  {id: "fr-CA-SylvieNeural", locale: "fr-CA", gender: "Female", name: "Sylvie"},
  {id: "fr-FR-VivienneMultilingualNeural", locale: "fr-FR", gender: "Female", name: "VivienneMultilingual"},
  {id: "fr-FR-RemyMultilingualNeural", locale: "fr-FR", gender: "Male", name: "RemyMultilingual"},
  {id: "fr-FR-DeniseNeural", locale: "fr-FR", gender: "Female", name: "Denise"},
  {id: "fr-FR-EloiseNeural", locale: "fr-FR", gender: "Female", name: "Eloise"},
  {id: "fr-FR-HenriNeural", locale: "fr-FR", gender: "Male", name: "Henri"},
  {id: "fr-CH-ArianeNeural", locale: "fr-CH", gender: "Female", name: "Ariane"},
  {id: "fr-CH-FabriceNeural", locale: "fr-CH", gender: "Male", name: "Fabrice"},
  {id: "gl-ES-RoiNeural", locale: "gl-ES", gender: "Male", name: "Roi"},
  {id: "gl-ES-SabelaNeural", locale: "gl-ES", gender: "Female", name: "Sabela"},
  {id: "ka-GE-EkaNeural", locale: "ka-GE", gender: "Female", name: "Eka"},
  {id: "ka-GE-GiorgiNeural", locale: "ka-GE", gender: "Male", name: "Giorgi"},
  {id: "de-AT-IngridNeural", locale: "de-AT", gender: "Female", name: "Ingrid"},
  {id: "de-AT-JonasNeural", locale: "de-AT", gender: "Male", name: "Jonas"},
  {id: "de-DE-SeraphinaMultilingualNeural", locale: "de-DE", gender: "Female", name: "SeraphinaMultilingual"},
  {id: "de-DE-FlorianMultilingualNeural", locale: "de-DE", gender: "Male", name: "FlorianMultilingual"},
  {id: "de-DE-AmalaNeural", locale: "de-DE", gender: "Female", name: "Amala"},
  {id: "de-DE-ConradNeural", locale: "de-DE", gender: "Male", name: "Conrad"},
  {id: "de-DE-KatjaNeural", locale: "de-DE", gender: "Female", name: "Katja"},
  {id: "de-DE-KillianNeural", locale: "de-DE", gender: "Male", name: "Killian"},
  {id: "de-CH-JanNeural", locale: "de-CH", gender: "Male", name: "Jan"},
  {id: "de-CH-LeniNeural", locale: "de-CH", gender: "Female", name: "Leni"},
  {id: "el-GR-AthinaNeural", locale: "el-GR", gender: "Female", name: "Athina"},
  {id: "el-GR-NestorasNeural", locale: "el-GR", gender: "Male", name: "Nestoras"},
  {id: "gu-IN-DhwaniNeural", locale: "gu-IN", gender: "Female", name: "Dhwani"},
  {id: "gu-IN-NiranjanNeural", locale: "gu-IN", gender: "Male", name: "Niranjan"},
  {id: "he-IL-AvriNeural", locale: "he-IL", gender: "Male", name: "Avri"},
  {id: "he-IL-HilaNeural", locale: "he-IL", gender: "Female", name: "Hila"},
  {id: "hi-IN-MadhurNeural", locale: "hi-IN", gender: "Male", name: "Madhur"},
  {id: "hi-IN-SwaraNeural", locale: "hi-IN", gender: "Female", name: "Swara"},
  {id: "hu-HU-NoemiNeural", locale: "hu-HU", gender: "Female", name: "Noemi"},
  {id: "hu-HU-TamasNeural", locale: "hu-HU", gender: "Male", name: "Tamas"},
  {id: "is-IS-GudrunNeural", locale: "is-IS", gender: "Female", name: "Gudrun"},
  {id: "is-IS-GunnarNeural", locale: "is-IS", gender: "Male", name: "Gunnar"},
  {id: "id-ID-ArdiNeural", locale: "id-ID", gender: "Male", name: "Ardi"},
  {id: "id-ID-GadisNeural", locale: "id-ID", gender: "Female", name: "Gadis"},
  { id: "iu-Latn-CA-SiqiniqNeural", locale: "iu-Latn-CA", gender: "Female", name: "Siqiniq" },
  { id: "iu-Latn-CA-TaqqiqNeural", locale: "iu-Latn-CA", gender: "Male", name: "Taqqiq" },
  { id: "iu-Cans-CA-SiqiniqNeural", locale: "iu-Cans-CA", gender: "Female", name: "Siqiniq" },
  { id: "iu-Cans-CA-TaqqiqNeural", locale: "iu-Cans-CA", gender: "Male", name: "Taqqiq" },
  
  ];


export const languages = [
    {
      lang: "English",
      langCode: "en",
      accentLang: [
        { countryCode: "US", countryName: "United States" },
        { countryCode: "UK", countryName: "United Kingdom" },
        { countryCode: "AU", countryName: "Australia" },
        { countryCode: "CA", countryName: "Canada" },
        { countryCode: "IN", countryName: "India" },
        { countryCode: "IE", countryName: "Ireland" },
        { countryCode: "KE", countryName: "Kenya" },
        { countryCode: "NZ", countryName: "New Zealand" },
        { countryCode: "NG", countryName: "Nigeria" },
        { countryCode: "PH", countryName: "Philippines" },
        { countryCode: "SG", countryName: "Singapore" },
        { countryCode: "ZA", countryName: "South Africa" },
        { countryCode: "TZ", countryName: "Tanzania" },
      ],
    },
  
    {
      lang: "Arabic",
      langCode: "ar",
      accentLang: [
        { countryCode: "DZ", countryName: "Algeria" },
        { countryCode: "BH", countryName: "Bahrain" },
        { countryCode: "EG", countryName: "Egypt" },
        { countryCode: "IQ", countryName: "Iraq" },
        { countryCode: "JO", countryName: "Jordan" },
        { countryCode: "KW", countryName: "Kuwait" },
        { countryCode: "LB", countryName: "Lebanon" },
        { countryCode: "LY", countryName: "Libya" },
        { countryCode: "MA", countryName: "Morocco" },
        { countryCode: "OM", countryName: "Oman" },
        { countryCode: "QA", countryName: "Qatar" },
        { countryCode: "SA", countryName: "Saudi Arabia" },
        { countryCode: "SY", countryName: "Syria" },
        { countryCode: "TN", countryName: "Tunisia" },
        { countryCode: "AE", countryName: "UAE" },
        { countryCode: "YE", countryName: "Yemen" },
      ],
    },
    {
      lang: "Mandarin Chinese",
      langCode: "zh",
      accentLang: [
        { countryCode: "CN", countryName: "Mainland China" },
        { countryCode: "TW", countryName: "Taiwan" },
        { countryCode: "HK", countryName: "Hong Kong" },
      ],
    },
    {
      lang: "Spanish",
      langCode: "es",
      accentLang: [
        { countryCode: "ES", countryName: "Spain" },
        { countryCode: "MX", countryName: "Mexico" },
        { countryCode: "AR", countryName: "Argentina" },
        { countryCode: "CO", countryName: "Colombia" },
        { countryCode: "PE", countryName: "Peru" },
        { countryCode: "VE", countryName: "Venezuela" },
        { countryCode: "CL", countryName: "Chile" },
        { countryCode: "EC", countryName: "Ecuador" },
        { countryCode: "GT", countryName: "Guatemala" },
        { countryCode: "CU", countryName: "Cuba" },
      ],
    },
    {
      lang: "Hindi",
      langCode: "hi",
      accentLang: [{ countryCode: "IN", countryName: "India" }],
    },
    {
      lang: "Bengali",
      langCode: "bn",
      accentLang: [
        { countryCode: "BD", countryName: "Bangladesh" },
        { countryCode: "IN", countryName: "India" },
      ],
    },
    {
      lang: "Portuguese",
      langCode: "pt",
      accentLang: [
        { countryCode: "PT", countryName: "Portugal" },
        { countryCode: "BR", countryName: "Brazil" },
      ],
    },
    {
      lang: "Russian",
      langCode: "ru",
      accentLang: [{ countryCode: "RU", countryName: "Russia" }],
    },
    {
      lang: "Japanese",
      langCode: "ja",
      accentLang: [{ countryCode: "JP", countryName: "Japan" }],
    },
    {
      lang: "French",
      langCode: "fr",
      accentLang: [
        { countryCode: "FR", countryName: "France" },
        { countryCode: "CA", countryName: "Canada" },
        { countryCode: "BE", countryName: "Belgium" },
        { countryCode: "CH", countryName: "Switzerland" },
        { countryCode: "MG", countryName: "Madagascar" },
      ],
    },
    {
      lang: "German",
      langCode: "de",
      accentLang: [
        { countryCode: "DE", countryName: "Germany" },
        { countryCode: "AT", countryName: "Austria" },
        { countryCode: "CH", countryName: "Switzerland" },
      ],
    },
    {
      lang: "Korean",
      langCode: "ko",
      accentLang: [{ countryCode: "KR", countryName: "South Korea" }],
    },
    {
      lang: "Italian",
      langCode: "it",
      accentLang: [{ countryCode: "IT", countryName: "Italy" }],
    },
    {
      lang: "Turkish",
      langCode: "tr",
      accentLang: [{ countryCode: "TR", countryName: "Turkey" }],
    },
    {
      lang: "Vietnamese",
      langCode: "vi",
      accentLang: [{ countryCode: "VN", countryName: "Vietnam" }],
    },
    {
      lang: "Persian",
      langCode: "fa",
      accentLang: [
        { countryCode: "IR", countryName: "Iran" },
        { countryCode: "AF", countryName: "Afghanistan (Dari)" },
      ],
    },
    {
      lang: "Swahili",
      langCode: "sw",
      accentLang: [
        { countryCode: "KE", countryName: "Kenya" },
        { countryCode: "TZ", countryName: "Tanzania" },
      ],
    },
    {
      lang: "Thai",
      langCode: "th",
      accentLang: [{ countryCode: "TH", countryName: "Thailand" }],
    },
    {
      lang: "Urdu",
      langCode: "ur",
      accentLang: [
        { countryCode: "PK", countryName: "Pakistan" },
        { countryCode: "IN", countryName: "India" },
      ],
    },
    {
      lang: "Punjabi",
      langCode: "pa",
      accentLang: [
        { countryCode: "IN", countryName: "India" },
        { countryCode: "PK", countryName: "Pakistan" },
      ],
    },
    {
      lang: "Dutch",
      langCode: "nl",
      accentLang: [
        { countryCode: "NL", countryName: "Netherlands" },
        { countryCode: "BE", countryName: "Belgium" },
      ],
    },
    {
      lang: "Polish",
      langCode: "pl",
      accentLang: [{ countryCode: "PL", countryName: "Poland" }],
    },
    {
      lang: "Ukrainian",
      langCode: "uk",
      accentLang: [{ countryCode: "UA", countryName: "Ukraine" }],
    },
    {
      lang: "Romanian",
      langCode: "ro",
      accentLang: [{ countryCode: "RO", countryName: "Romania" }],
    },
    {
      lang: "Greek",
      langCode: "el",
      accentLang: [{ countryCode: "GR", countryName: "Greece" }],
    },
    {
      lang: "Hungarian",
      langCode: "hu",
      accentLang: [{ countryCode: "HU", countryName: "Hungary" }],
    },
    {
      lang: "Czech",
      langCode: "cs",
      accentLang: [{ countryCode: "CZ", countryName: "Czech Republic" }],
    },
    {
      lang: "Slovak",
      langCode: "sk",
      accentLang: [{ countryCode: "SK", countryName: "Slovakia" }],
    },
    {
      lang: "Serbian",
      langCode: "sr",
      accentLang: [{ countryCode: "RS", countryName: "Serbia" }],
    },
    {
      lang: "Croatian",
      langCode: "hr",
      accentLang: [{ countryCode: "HR", countryName: "Croatia" }],
    },
    {
      lang: "Bosnian",
      langCode: "bs",
      accentLang: [{ countryCode: "BA", countryName: "Bosnia and Herzegovina" }],
    },
    {
      lang: "Albanian",
      langCode: "sq",
      accentLang: [{ countryCode: "AL", countryName: "Albania" }],
    },
  ];


